logging:
  level:
    com.atomist.spring.agent: DEBUG

atomist:
  enabled: true
  debug: true
  url: 'https://webhook.atomist.com/atomist/application/teams/${ATOMIST_TEAM}'
  environment:
    domain: '${ATOMIST_ENVIRONMENT:${vcap.application.space_name:development}}'
    pod: '${HOSTNAME:${random.value}}'
